### PR TITLE
Add requirements, ruff pre-commit hook and pytest config

### PR DESCRIPTION
**Pull request by horrormyth**

### CODE REVIEW

**Comment by horrormyth** [comment]
Will add the guidelines in another PR

**Comment by sumanashrestha** [comment]
looks a bit overkill for a project with a single file and 200 LOC tbh.

will this add any additional steps for somebody trying to just run the code ?

**Comment by haruBlank00** [comment]
> looks a bit overkill for a project with a single file and 200 LOC tbh.
> 
> will this add any additional steps for somebody trying to just run the code ?

No it won't add any additional steps to just run the code.
These are  formatter and guides for contributors.
It will only effect the developers by making sure everyone share the same config since everyone might have their own config locally

**Comment by horrormyth** [comment]
> Will add the guidelines in another PR

https://github.com/moest-np/center-randomize/pull/32

**Pull request merged**
