### PR TITLE
Added Legend in map for clear identification of school and center

### PR DESCRIPTION
**Pull request by nirmala-sharma**
Legend helps to distinguish between schools and centers on the map. Red marker denotes center and blue marker denotes school.

Tested in chrome, edge, firefox browser.

### CODE REVIEW

**Comment by sujanshresstha** [comment]
There is import conflict, where the `Template` class was ambiguously imported from both `jinja2` and `pipes`, leading to a TypeError at runtime.
Remove or comment out this line `from pipes import Template`

**Comment by sujanshresstha** [comment]
There is import conflict, where the `Template` class was ambiguously imported from both `jinja2 `and `pipes`, leading to a TypeError at runtime.
Remove or comment out this line `from pipes import Template`

**Comment by nirmala-sharma** [comment]
> There is import conflict, where the `Template` class was ambiguously imported from both `jinja2 `and `pipes`, leading to a TypeError at runtime. Remove or comment out this line `from pipes import Template`

Issue Resolved. Thank You!

**Comment by sumanashrestha** [comment]
Thank you @nirmala-sharma for your continued support on this.

**Pull request merged**
